spring.application.name=chatcesur

# La URL de Ollama
spring.ai.ollama.base-url=http://localhost:11434

# El nombre del modelo
spring.ai.ollama.chat.options.model=qwen2.5:1.5b

# Nivel de "creatividad" (0.0 a 1.0)
spring.ai.ollama.chat.options.temperature=0.7

spring.security.user.name=admin
spring.security.user.password=1234